### ISSUE TITLE
Why TC3?

### ISSUE THREAD

**Issue by jondoesntgit** [Dennis-van-Gils/SAMD51_InterruptTimer#2]
How does your code know to select TC3 instead of say, TC4 or TC0?

**Comment by jamman83** [comment]
In the source code it specifies to set up the registers for TC3 indicated by "TC3->'whatever register'"

TC3 is defined in file "AppData\Local\Arduino15\packages\arduino\tools\CMSIS-Atmel\1.2.0\CMSIS\Device\ATMEL\samd51\include\component\tcc.h" It does all of the tedious work of pointing to register addresses for you, so all you have to do is name the peripheral/register you want to read/write as it is in the datasheet and bada-bing bada-boom.

**Comment by jondoesntgit** [comment]
Thanks
