### ISSUE TITLE
TImer interrupt mishandling usb call backs

### ISSUE THREAD

**Issue by lalitheranti** [Dennis-van-Gils/SAMD51_InterruptTimer#4]
Hi,

I am using adafruit itsybitsy M4 , and using the lib for timer interruppts. I have in my code USB call backs for tinyUSB stack which shows up the flash as a storage drive. when using the lib for interrupt to read the sensor data, suddenly the usb stack is missing and does not show up as drive. Is it a timing issue or what could be the possible solution? can anyone help?

Lalith.

**Comment by Dennis-van-Gils** [comment]
Please be aware that improper use of interrupt service routines can mess with other serial communication, like you seem to experience. It is not impossible to get both to work at the same time, but it requires in-depth knowledge. Without knowing your specific code it is hard to help you. Not that I would have the time to do so, I'm afraid.

I hope you have already found more information on the topic and have found a solution. I'm closing this issue as it's not directly related to this library, but is related to the microcontroller machinery in general.
