### ISSUE TITLE
Questions: fastest possible interrupt frequency?

### ISSUE THREAD

**Issue by Elmi77** [Dennis-van-Gils/SAMD51_InterruptTimer#7]
Hi,

not a bugreport but a short question: assumed the ISR does not need any additional time, what is the fastest interrupt frequency/the shortest time that can be done with this library?

Thanks :-)

**Comment by Dennis-van-Gils** [comment]
That really depends on how the clock registers are set up, but typically a period of one to a few microseconds should be attainable.
